In [ ]:
########################## Assignment 3 ######################

In [ ]:
#Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [8]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

#using list comprehension 
list_of_sentences = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in list_of_sentences:
     print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [ ]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.

In [10]:
def div_by_zero():
     return 5/0
#try/except block
#First try block is executed, we write funtion/code which might cause an exception
try:
     div_by_zero()
#The except clause is executed only when type matches the exception named after the except keyword,else if an unhandled exception, execution stops and throws exception
except ZeroDivisionError as e: 
     print("Exception occured:", e)

Exception occured: division by zero


In [ ]:
#Write a function so that the columns of the output matrix are powers of the input vector.

In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])   # x: 1D input array
N = 3                        #N: number of coloumn in output
np.vander(x, N)
 


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [3]:
np.column_stack([x**(N-1-i) for i in range(N)])    # i-th output column is the input vector to the power of N - i - 1

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [4]:
x = np.array([1, 2, 3, 4])
np.vander(x)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [5]:
np.linalg.det(np.vander(x)) #determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector

12.000000000000005

In [6]:
(4-3)*(4-2)*(4-1)*(3-2)*(3-1)*(2-1)

12